service: CBCAP

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  stage: dev

functions:
  FetchReport:
    handler: FetchReport.lambda_handler
    memorySize: 512
    timeout: 60
    role: arn:aws:iam::639015715993:role/lambda-vpc-execution-role
    versionFunctions: false
plugins:
  - serverless-python-requirements
